# ¸_____¸_____¸  
#  ╲__¸ ┊ ¸__╱   
# ¸_  ┊ ┊ ┊ ___  James Gober
# ┊ [_┊ ┊ ┊_] ┊  Contact@JamesGober.com
# ┊_____A_____┊  https://JamesGober.com
# JAMES ⬡ GOBER   
# ===================================================
[workspace]
members = [
    "modcli"
]
resolver = "2"
