# cargo-deny configuration
# See: https://embarkstudios.github.io/cargo-deny/

[graph]
# Skip dev graph duplication in checks
all-features = true

[advisories]
# Keep config version-agnostic: only use stable keys
vulnerability = "deny"
unsound = "deny"
ignore = []

[licenses]
# Allowed licenses list (adjust as needed)
allow = [
  "Apache-2.0",
  "MIT",
  "BSD-3-Clause",
  "BSD-2-Clause",
  "ISC",
  "Zlib",
]
# Optional: minimum confidence for license detection (0.0 - 1.0)
confidence-threshold = 0.8

[licenses.private]
# Treat private workspace members as private
ignore = true

[bans]
multiple-versions = "warn"
wildcards = "deny"
# Example: disallow old log crates
# deny = [ { name = "time", version = "<0.3" } ]

[sources]
unknown-registry = "deny"
unknown-git = "warn"
# Allow crates.io by default
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
