name: Release

on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish to crates.io (true/false)'
        required: true
        default: 'false'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cargo publish dry-run
        run: cargo publish --dry-run

      - name: Publish crates (requires manual enable)
        if: ${{ github.event.inputs.publish == 'true' }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --token "${{ env.CARGO_REGISTRY_TOKEN }}"
